name: Docs Quality

on:
  pull_request:
    paths:
      - "**/*.md"
  push:
    paths:
      - "**/*.md"

jobs:
  spell_style_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # codespell
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: |
          codespell --ignore-words-list=crate,teh --skip="*.png,*.jpg,*.svg" --quiet-level=2 .

      # markdownlint
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install markdownlint-cli
        run: npm i -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint "**/*.md" -c .markdownlint.json

      # proselint (non-blocking; make it advisory)
      - name: Install proselint
        run: pip install proselint
      - name: Run proselint (advisory)
        run: |
          proselint "**/*.md" || true

      # vale (optional)
      - name: Install Vale
        run: |
          curl -s https://api.github.com/repos/errata-ai/vale/releases/latest \
          | grep "browser_download_url.*Linux_64-bit.tar.gz" \
          | cut -d '"' -f 4 | wget -qi -
          tar -xzf vale_*Linux_64-bit.tar.gz
          sudo mv vale /usr/local/bin/
          vale -v
      - name: Run Vale
        run: |
          if [ -f ".vale.ini" ]; then
            vale sync || true
            vale .
          else
            echo "No .vale.ini found; skipping Vale."
          fi
